#ifndef __PROJECT_CFG_H__
#define __PROJECT_CFG_H__

#define TCT_PRESSURE_SINGAL_ENABLE 1
#define IO_CTRL_EVENT_ENABLE 1
#define PRESSURE_SENSOR_ENABLE 1
#define LOCAL_ADDRESS 3

/*********µç»úÅäÖÃ********/
#define MOTOR_ZERO_COORDINATE 4800
#define MOTOR_MAX_COORDINATE 80000
#define MOTOR_LOST_ENDURE_CONTINUE 2400
#define MOTOR_LOST_ENDURE_STOP 3600
#define MOTOR_ZERO_TRIG_VOL 0
#define MOTOR_DIR_VOL 1
#define MOTOR_ENB_VOL 0
#define MOTOR_HALF_VOL 0
#define MOTOR_ENABLE_ZERO_MAKEUP 1
#define MOTOR_BACK_ZERO_SPEED_MODE 0
#define MOTOR_SUBDIVISIION 16
#define MOTOR_CURRENT_LEVEL 15
#define MOTOR_HOLD_LEVEL 5
#define MOTOR_RS_COORDINATE 2400

#endif
